allowBuilds:
  "@parcel/watcher": true
  esbuild: true

catalogs:
  dev:
    typescript: ^6.0.3
  prod:
    nuxt: ^4.4.5
  fmt:
    oxfmt: ^0.49.0
  lint:
    oxlint: ^1.64.0
    oxlint-tsgolint: ^0.22.1
  hooks:
    husky: ^9.1.7
    lint-staged: ^17.0.4

publicHoistPattern:
  - vue
  - vue-router
